### ISSUE TITLE
Replacing ElementalArea with Injector causes infinite loop when generating GraphQL admin schema

### ISSUE THREAD

**Issue by AljosaB** [dnadesign/silverstripe-elemental#1014]
## Affected Version
SS 4.11.2
Elemental 4.9.4

## Steps to Reproduce
**/app/src/ChangedElementalArea.php**
```php
<?php

namespace Aljosa\DataObjects;

use DNADesign\Elemental\Models\ElementalArea;

class ChangedElementalArea extends ElementalArea
{
    // it happens even if there is no code here
}
```

**/app/_config/injectors.yml**
```yml
SilverStripe\Core\Injector\Injector:
  DNADesign\Elemental\Models\ElementalArea:
    class: Aljosa\DataObjects\ChangedElementalArea
```

**Run**
```bash
/vendor/silverstripe/framework$ php cli-script.php dev/graphql/build schema=admin flush=1
```
(which is also automatically executed every dev/build)

**Error**
```
[INFO]: --- Building schema "admin" ---
ERROR [Emergency]: Uncaught Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
IN GET dev/graphql/build
Line 50 in /vendor/silverstripe/framework/src/Core/Injector/SilverStripeServiceConfigurationLocator.php
```

## Additional info
- it breaks loading all elemental areas in CMS (GraphQL ajax calls)
- it has something to do with

**/vendor/dnadesign/silverstripe-elemental/_graphql/models.yml**
```yml
# Expose access to Elements via Page -> ElementalArea -> Elements (see resolver)
DNADesign\Elemental\Models\ElementalArea:
  fields:
    id: true
    elements:
      plugins:
        paginateList: false
  operations:
    readOne: true
```
